### ISSUE TITLE
ling佬，mhr的bhvt使用时会报错

### ISSUE THREAD

**Issue by xiaoniaoruqin** [lingsamuel/lingsamuel#1]
REF上会有一个这样的报错，BHVT窗口也没有反应，不知道是哪里出了问题
![怪猎报错](https://github.com/lingsamuel/lingsamuel/assets/149473945/a26467c9-c6e2-4610-9acd-6f961ac409cf)

**Comment by lingsamuel** [comment]
请去PR下面回复
